// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "Drive.h"
Drive::Drive() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveTrain);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
Drive::Drive(double direction, double velocity, double timeout, bool usegyro) {
	Requires(Robot::driveTrain);
	radian = direction;
	speed = velocity;
	useGyro = usegyro;
	SetTimeout(timeout);
	gyroAngle = 0;
}
// Called just before this Command runs the first time
void Drive::Initialize() {
	gyroAngle = Robot::driveTrain->gyroscope->GetAngle();
}
// Called repeatedly when this Command is scheduled to run
void Drive::Execute() {
	if (useGyro) {
		GyroRad = (Robot::driveTrain->gyroscope->GetAngle()-gyroAngle)*3.14159/180;
	}
	else
	{
		GyroRad = 0;
	}
	
	if(speed > 0)
		Robot::driveTrain->Steer(radian + GyroRad, speed, .5);
	else
		Robot::driveTrain->Steer(radian - GyroRad, speed, .5);
}
// Make this return true when this Command no longer needs to run execute()
bool Drive::IsFinished() {
	return IsTimedOut();
}
// Called once after isFinished returns true
void Drive::End() {
	Robot::driveTrain->Steer(radian, 0, .5);
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void Drive::Interrupted() {
	Robot::driveTrain->Steer(radian, 0, .5);
}
