// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "FollowLine.h"
FollowLineTask followline;
FollowLine::FollowLine(float speed, float driveangle, float twistangle, float timeout) {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveTrain);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	X = speed*sin(driveangle*3.14159/180);
	Y = speed*cos(driveangle*3.14159/180);
	TwistAngle = twistangle;
	Timeout = timeout;
}
// Called just before this Command runs the first time
void FollowLine::Initialize() {
	SetTimeout(Timeout);
	followline.SetDriveVariables(X,Y,TwistAngle);
	followline.Start();
}
// Called repeatedly when this Command is scheduled to run
void FollowLine::Execute() {
	
}
// Make this return true when this Command no longer needs to run execute()
bool FollowLine::IsFinished() {
	return IsTimedOut(); // || Robot::driveTrain->frontLeftDrive->Get() == 0;
}
// Called once after isFinished returns true
void FollowLine::End() {
	followline.Pause();
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void FollowLine::Interrupted() {
	followline.Pause();
}
