// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "ResetGyro.h"
ResetGyro::ResetGyro() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	SetRunWhenDisabled(true);
}
// Called just before this Command runs the first time
void ResetGyro::Initialize() {
	
}
// Called repeatedly when this Command is scheduled to run
void ResetGyro::Execute() {
	Robot::oi->setOIDigitalOutput1(true);
	Robot::oi->setOIDigitalOutput2(true);
	Robot::oi->setOIDigitalOutput3(true);
	Robot::oi->setOIDigitalOutput4(true);
	Robot::oi->setOIDigitalOutput5(true);
	Robot::oi->setOIDigitalOutput6(true);
	Robot::oi->setOIDigitalOutput7(true);
	Robot::oi->setOIDigitalOutput8(true);
}
// Make this return true when this Command no longer needs to run execute()
bool ResetGyro::IsFinished() {
	return !DriverStation::GetInstance()->IsDisabled() || Robot::driveTrain->ZeroGyro(10.0);
}
// Called once after isFinished returns true
void ResetGyro::End() {
	Robot::oi->setOIDigitalOutput1(false);
	Robot::oi->setOIDigitalOutput2(false);
	Robot::oi->setOIDigitalOutput3(false);
	Robot::oi->setOIDigitalOutput4(false);
	Robot::oi->setOIDigitalOutput5(false);
	Robot::oi->setOIDigitalOutput6(false);
	Robot::oi->setOIDigitalOutput7(false);
	Robot::oi->setOIDigitalOutput8(false);	
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ResetGyro::Interrupted() {
}
