// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "ShootCommand.h"
ShootCommand::ShootCommand() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
}
// Called just before this Command runs the first time
void ShootCommand::Initialize() {
  printf("ShootCommand called \r\n");
}
// Called repeatedly when this Command is scheduled to run
void ShootCommand::Execute() {
	RobotMap::shooter->Set(1);
}
// Make this return true when this Command no longer needs to run execute()
bool ShootCommand::IsFinished() {
	if(RobotMap::shooterpot->GetVoltage() > 1.0 && RobotMap::shooterpot->GetVoltage() < 1.5)
		return true;
	else
		return false;
}
// Called once after isFinished returns true
void ShootCommand::End() {
	RobotMap::shooter->Set(0);
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ShootCommand::Interrupted() {
	RobotMap::shooter->Set(0);
}
