// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "ShootBackCommand.h"
ShootBackCommand::ShootBackCommand() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
}
// Called just before this Command runs the first time
void ShootBackCommand::Initialize() {
  printf("ShootBackCommand called \r\n");
}
// Called repeatedly when this Command is scheduled to run
void ShootBackCommand::Execute() {
//	RobotMap::shooter->Set(-1); //DANGER - for calibration only
}
// Make this return true when this Command no longer needs to run execute()
bool ShootBackCommand::IsFinished() {
	return false;
}
// Called once after isFinished returns true
void ShootBackCommand::End() {
	RobotMap::shooter->Set(0);
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ShootBackCommand::Interrupted() {
	RobotMap::shooter->Set(0);
}
