// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "TurnRobot.h"
TurnRobot::TurnRobot(float angle, float tolerance) {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveTrain);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Angle = angle;
	Tolerance = tolerance;
}
// Called just before this Command runs the first time
void TurnRobot::Initialize() {
	ontarget = 0;
}
// Called repeatedly when this Command is scheduled to run
void TurnRobot::Execute() {
	if(Angle - Robot::driveTrain->gyroscope->GetAngle() > 0)
		Robot::driveTrain->Steer(0, ((Angle - Robot::driveTrain->gyroscope->GetAngle())/250 + .18), 0.5);
	else
		Robot::driveTrain->Steer(0, ((Angle - Robot::driveTrain->gyroscope->GetAngle())/250 - .18), 0.5);
	
	if(fabs(Angle - Robot::driveTrain->gyroscope->GetAngle()) < Tolerance)
		ontarget ++;
}
// Make this return true when this Command no longer needs to run execute()
bool TurnRobot::IsFinished() {
	return ontarget > 10;
}
// Called once after isFinished returns true
void TurnRobot::End() {
	Robot::driveTrain->Steer(0, 0, 0.5);
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void TurnRobot::Interrupted() {
}
