// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"

AnalogChannelVolt* RobotMap::driveTrainFrontRightPos = NULL;
SpeedController* RobotMap::driveTrainFrontRightSteer = NULL;
PIDController* RobotMap::driveTrainFrontRight = NULL;
AnalogChannelVolt* RobotMap::driveTrainFrontLeftPos = NULL;
SpeedController* RobotMap::driveTrainFrontLeftSteer = NULL;
PIDController* RobotMap::driveTrainFrontLeft = NULL;
AnalogChannelVolt* RobotMap::driveTrainRearRightPos = NULL;
SpeedController* RobotMap::driveTrainRearRightSteer = NULL;
PIDController* RobotMap::driveTrainRearRight = NULL;
AnalogChannelVolt* RobotMap::driveTrainRearLeftPos = NULL;
SpeedController* RobotMap::driveTrainRearLeftSteer = NULL;
PIDController* RobotMap::driveTrainRearLeft = NULL;
SpeedController* RobotMap::driveTrainFrontLeftDrive = NULL;
SpeedController* RobotMap::driveTrainFrontRightDrive = NULL;
SpeedController* RobotMap::driveTrainRearLeftDrive = NULL;
SpeedController* RobotMap::driveTrainRearRightDrive = NULL;

SpeedController* RobotMap::shooter = NULL;
//PIDController* RobotMap::shooterpid = NULL;
AnalogChannelVolt* RobotMap::shooterpot = NULL;

Relay* RobotMap::leftwing = NULL;
Relay* RobotMap::rightwing = NULL;
Relay* RobotMap::leftroller = NULL;
Relay* RobotMap::rightroller = NULL;

//SpeedController* RobotMap::rightarm = NULL;
//SpeedController* RobotMap::leftarm = NULL;
//AnalogChannelVolt* RobotMap::leftpot = NULL;
//AnalogChannelVolt* RobotMap::rightpot = NULL;
//PIDController* RobotMap::leftpid = NULL;
//PIDController* RobotMap::rightpid = NULL;

//Relay* RobotMap::reardeploy = NULL;

Solenoid* RobotMap::rightwingin = NULL;
Solenoid* RobotMap::rightwingout = NULL;
Solenoid* RobotMap::leftwingin = NULL;
Solenoid* RobotMap::leftwingout = NULL;


Compressor* RobotMap::compressor = NULL;

DigitalModule* RobotMap::i2cmodule = NULL;
I2C* RobotMap::m_i2c = NULL;

#define CONTINUOUS true
#define P 1.0
#define I 0.0
#define D 0.2
#define F 0.0
#define POTMIN 0.0
#define POTMAX 5.0
#define STEERPOW  1.0
#define TOLERANCE 0.2
#define PERIOD .02

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	//LiveWindow* lw = LiveWindow::GetInstance();

	compressor = new Compressor(1,2);
	rightwingin = new Solenoid(1);
	rightwingout = new Solenoid(2);
	leftwingin = new Solenoid(3);
	leftwingout = new Solenoid(4);

	driveTrainFrontRightDrive = new Talon(1, 4);
	driveTrainFrontRightPos = new AnalogChannelVolt(1, 1);
	driveTrainFrontRightSteer = new Talon(1, 6);
	driveTrainFrontRight = new PIDController(P, I, D, F,  driveTrainFrontRightPos,
                                           driveTrainFrontRightSteer, PERIOD);
	driveTrainFrontRight->SetContinuous(CONTINUOUS); 
  	driveTrainFrontRight->SetAbsoluteTolerance(TOLERANCE); 
        driveTrainFrontRight->SetInputRange(POTMIN, POTMAX);
        driveTrainFrontRight->SetOutputRange(-STEERPOW, STEERPOW);

	driveTrainFrontLeftDrive = new Talon(1, 3);
	driveTrainFrontLeftPos = new AnalogChannelVolt(1, 3);
	driveTrainFrontLeftSteer = new Talon(1, 7);
	driveTrainFrontLeft = new PIDController(P, I, D, F,  driveTrainFrontLeftPos,
                                          driveTrainFrontLeftSteer, PERIOD);
	driveTrainFrontLeft->SetContinuous(CONTINUOUS); 
  	driveTrainFrontLeft->SetAbsoluteTolerance(TOLERANCE); 
        driveTrainFrontLeft->SetInputRange(POTMIN, POTMAX);
        driveTrainFrontLeft->SetOutputRange(-STEERPOW, STEERPOW);

	driveTrainRearRightDrive = new Talon(1, 1);
	driveTrainRearRightPos = new AnalogChannelVolt(1, 2);
	driveTrainRearRightSteer = new Talon(1, 5);
	driveTrainRearRight = new PIDController(P, I, D, F,  driveTrainRearRightPos,
                                          driveTrainRearRightSteer, PERIOD);
	driveTrainRearRight->SetContinuous(CONTINUOUS); 
  	driveTrainRearRight->SetAbsoluteTolerance(TOLERANCE); 
        driveTrainRearRight->SetInputRange(POTMIN, POTMAX);
        driveTrainRearRight->SetOutputRange(-STEERPOW, STEERPOW);

	driveTrainRearLeftDrive = new Talon(1, 2);
	driveTrainRearLeftPos = new AnalogChannelVolt(1, 4);
	driveTrainRearLeftSteer = new Talon(1, 8);
	driveTrainRearLeft = new PIDController(P, I, D, F,  driveTrainRearLeftPos,
                                         driveTrainRearLeftSteer, PERIOD);
	driveTrainRearLeft->SetContinuous(CONTINUOUS); 
  	driveTrainRearLeft->SetAbsoluteTolerance(TOLERANCE); 
        driveTrainRearLeft->SetInputRange(POTMIN, POTMAX);
        driveTrainRearLeft->SetOutputRange(-STEERPOW, STEERPOW);

	shooter = new Talon(1, 9);
	shooter->Set(0);
	shooterpot = new AnalogChannelVolt(1, 5);
//	shooterpid = new PIDController(P, I, D, F,  shooterpot,
//                                          shooter, PERIOD);

//	rightarm = new Talon(1, 10);
//	rightarm->Set(0);

//	leftarm = new CANJaguar(1);
//	leftarm->Set(0);

//	rightwing = new Relay(4);
//	leftwing = new Relay(2);
	leftroller = new Relay(3);
	rightroller = new Relay(1);
//	reardeploy = new Relay(5);
//	leftpot = new AnalogChannelVolt(1, 6);
//	rightpot = new AnalogChannelVolt(1, 7);
//	leftpid = new PIDController(3, 0, 0, 0,  leftpot,
//                                          leftarm, PERIOD);
//	leftpid->SetContinuous(CONTINUOUS); 
//  	leftpid->SetAbsoluteTolerance(.01); 
//      leftpid->SetInputRange(0.0, 5.0);
//      leftpid->SetOutputRange(-.5, .5);

//	rightpid = new PIDController(3, 0, 0, 0,  rightpot,
//                                          rightarm, PERIOD);
//	rightpid->SetContinuous(CONTINUOUS); 
//  	rightpid->SetAbsoluteTolerance(.01); 
//      rightpid->SetInputRange(0.0, 5.0);
//      rightpid->SetOutputRange(-.5, .5);

	m_i2c = DigitalModule::GetInstance(1)->GetI2C(0x04 << 1);
	compressor->Start();
}
