// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "Robot.h"
#include "Commands/NoneAuto.h"
#include "Commands/threeballauto.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INITIALIZATION
DriveTrain* Robot::driveTrain = 0;
Picker* Robot::picker = 0;

OI* Robot::oi = 0;
char Robot::visionpacket = '8';

STATUS udpServer (void);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INITIALIZATION
void Robot::RobotInit() {
	RobotMap::init();
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	driveTrain = new DriveTrain();
	picker = new Picker();
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	// This MUST be here. If the OI creates Commands (which it very likely
	// will), constructing it during the construction of CommandBase (from
	// which commands extend), subsystems are not guaranteed to be
	// yet. Thus, their requires() statements may grab null pointers. Bad
	// news. Don't move it.
	oi = new OI();
	lw = LiveWindow::GetInstance();
	// instantiate the command used for the autonomous period
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS
	autonomousCommand = new AutonomousCommand();
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS
	
	DS = DriverStation::GetInstance();
	Prefs = Preferences::GetInstance();
	File = RAWCConstants::getInstance();
	Robot::driveTrain->SetWheelbase(21.5/2, 21.5/2, 21.5/2);

  	printf("getting offsets\n");
	
	FLOffset = File->getValueForKey("FLOff");
	FROffset = File->getValueForKey("FROff");
	RLOffset = File->getValueForKey("RLOff");
	RROffset = File->getValueForKey("RROff");

  	printf("done getting offsets\n");
	
	Robot::driveTrain->SetOffsets(FLOffset, FROffset, RLOffset, RROffset);
	
	Robot::driveTrain->frontLeftPos->Start();
	Robot::driveTrain->frontRightPos->Start();
	Robot::driveTrain->rearLeftPos->Start();
	Robot::driveTrain->rearRightPos->Start();

	Robot::driveTrain->frontLeft->Enable();
	Robot::driveTrain->frontRight->Enable();
	Robot::driveTrain->rearLeft->Enable();
	Robot::driveTrain->rearRight->Enable();

	if(!Prefs->ContainsKey("CamStop"))
		Prefs->PutFloat("CamStop",1.25);
	
//	autoChooser = new SendableChooser();
//	autoChooser->AddDefault("1. 3ballauto", new ThreeBallAuto());
//	autoChooser->AddObject("2. None", new NoneAuto());
//	SmartDashboard::PutData("AutonomousChooser", autoChooser);


	task = new Task("udpServer", (FUNCPTR) udpServer, 100);
	task->Start((UINT32)this);

//	if( taskSpawn("udpServer", 100, 0, 10000,
//		(FUNCPTR) udpServer, 0,0,0,0,0,0,0,0,0,0) == ERROR)
//	{
//		printf("taskSpawn udpserver failed\n");
//
//	}

    table = NetworkTable::GetTable("datatable");
    serial_port = new SerialPort(57600);
    uint8_t update_rate_hz = 50;
    imu = new IMUAdvanced(serial_port,update_rate_hz);
    //imu = new IMU(serial_port,update_rate_hz);
    if ( imu ) {
      LiveWindow::GetInstance()->AddSensor("IMU", "Gyro", imu);
    }
    first_iteration = true;
}

void Robot::DisabledInit(){
        RobotMap::m_i2c->Write(1, 0);
}
	
void Robot::DisabledPeriodic(){
	Scheduler::GetInstance()->Run();

    if ( first_iteration ) {
        bool is_calibrating = imu->IsCalibrating();
        if ( !is_calibrating ) {
            Wait( 0.3 );
            imu->ZeroYaw();
            first_iteration = false;
        }
    }
    updateNav6();
}

void Robot::AutonomousInit() {
	Robot::driveTrain->SetDriveBackFlag(false);
//	autonomousCommand = (Command*) autoChooser->GetSelected();
	autonomousCommand = new ThreeBallAuto();
	if (autonomousCommand != NULL)
		autonomousCommand->Start();
}
	
void Robot::AutonomousPeriodic() {
	Scheduler::GetInstance()->Run();
    updateNav6();
}	
void Robot::TeleopInit() {
	// This makes sure that the autonomous stops running when
	// teleop starts running. If you want the autonomous to 
	// continue until interrupted by another command, remove
	// this line or comment it out.
	
	autonomousCommand->Cancel();
	Robot::picker->RetractRear();
	Robot::driveTrain->outputLED();
}
void Robot::TeleopPeriodic() {
	if (autonomousCommand != NULL)
		Scheduler::GetInstance()->Run();
    updateNav6();
		
}
void Robot::TestPeriodic() {
	lw->Run();
    updateNav6();
}

void Robot::updateNav6() {
    SmartDashboard::PutBoolean( "IMU_Connected", imu->IsConnected());
    SmartDashboard::PutNumber("IMU_Yaw", imu->GetYaw());
    SmartDashboard::PutNumber("IMU_Pitch", imu->GetPitch());
    SmartDashboard::PutNumber("IMU_Roll", imu->GetRoll());
    SmartDashboard::PutNumber("IMU_CompassHeading", imu->GetCompassHeading());
    SmartDashboard::PutNumber("IMU_Update_Count", imu->GetUpdateCount());
    SmartDashboard::PutNumber("IMU_Byte_Count", imu->GetByteCount());

    SmartDashboard::PutNumber("IMU_Accel_X", imu->GetWorldLinearAccelX());
    SmartDashboard::PutNumber("IMU_Accel_Y", imu->GetWorldLinearAccelY());
    SmartDashboard::PutBoolean("IMU_IsMoving", imu->IsMoving());
    SmartDashboard::PutNumber("IMU_Temp_C", imu->GetTempC());
    SmartDashboard::PutBoolean("IMU_IsCalibrating", imu->IsCalibrating());
}


START_ROBOT_CLASS(Robot);
