// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "Climber.h"
#include "../Robotmap.h"
#include "../Commands/OperatorClimb.h"
Climber::Climber() : Subsystem("Climber") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	climbLeft = RobotMap::climberClimbLeft;
	climbRight = RobotMap::climberClimbRight;
	angleLeft = RobotMap::climberAngleLeft;
	angleRight = RobotMap::climberAngleRight;
	climberDistance = RobotMap::climberClimberDistance;
	extendLimit = RobotMap::climberExtendLimit;
	retractLimit = RobotMap::climberRetractLimit;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void Climber::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	SetDefaultCommand(new OperatorClimb());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
// Put methods for controlling this subsystem
// here. Call these from Commands.
void Climber::RunClimber(float speed) {
	if ((speed < 0 && !retractLimit->Get()) || (speed > 0 && !extendLimit->Get())) {
		Robot::climber->climbLeft->Set(0);
		Robot::climber->climbRight->Set(0);
	}
	else {
		Robot::climber->climbLeft->Set(speed);
		Robot::climber->climbRight->Set(speed);
	}
}
void Climber::CurrentLimit(){
	float currentlimit = 20;
	float currenttimeout = 1.5;
	float timeoutreset = 1.5;
	if((angleLeft->GetOutputCurrent() > currentlimit || angleRight->GetOutputCurrent() > currentlimit)){
		if(SOTimer < GetClock()){
			SOTimer = GetClock()+currenttimeout;
		}
		else{
			SOTimer = GetClock() + timeoutreset;
			}
	}
	
}
int Climber::GetCorrectedAngle() {
	return 0; //anglePos->GetAverageValue() - angleOffset;
}
