// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "DriveTrain.h"
#include "../Robotmap.h"
#include "../Commands/CrabDrive.h"
#include "../Commands/SteerDrive.h"
DriveTrain::DriveTrain(): 
Subsystem("DriveTrain")
{
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	frontRightPos = RobotMap::driveTrainFrontRightPos;
	frontRightSteer = RobotMap::driveTrainFrontRightSteer;
	frontRight = RobotMap::driveTrainFrontRight;
	frontLeftPos = RobotMap::driveTrainFrontLeftPos;
	frontLeftSteer = RobotMap::driveTrainFrontLeftSteer;
	frontLeft = RobotMap::driveTrainFrontLeft;
	rearRightPos = RobotMap::driveTrainRearRightPos;
	rearRightSteer = RobotMap::driveTrainRearRightSteer;
	rearRight = RobotMap::driveTrainRearRight;
	rearLeftPos = RobotMap::driveTrainRearLeftPos;
	rearLeftSteer = RobotMap::driveTrainRearLeftSteer;
	rearLeft = RobotMap::driveTrainRearLeft;
	frontLeftDrive = RobotMap::driveTrainFrontLeftDrive;
	frontRightDrive = RobotMap::driveTrainFrontRightDrive;
	rearLeftDrive = RobotMap::driveTrainRearLeftDrive;
	rearRightDrive = RobotMap::driveTrainRearRightDrive;
	gyroscope = RobotMap::driveTrainGyroscope;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	wheelSpokeCounter = RobotMap::wheelSpokeCounter;
	GyroZeroFlag = false;
	GyroZeroTime = GetClock();
	FLInv = 1;
	FRInv = 1;
	RRInv = 1;
	RLInv = 1;
}
    
void DriveTrain::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	SetDefaultCommand(new SteerDrive());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	driveFront = true;
}
// Put methods for controlling this subsystem
// here. Call these from Commands.
void DriveTrain::SetWheelbase(float w, float x, float y) {
	W=w;
	X=x;
	Y=y;
}
void DriveTrain::SetMaxSpeed(float MaxSpeed) {
	MaxSpeed = maxspeed;
}
void DriveTrain::SetGyroReference(){
	gyroreference = gyroscope->GetAngle();
}
void DriveTrain::SetOffsets(int FLOff, int FROff, int RLOff, int RROff) {
	FLOffset = FLOff;
	FROffset = FROff;
	RLOffset = RLOff;
	RROffset = RROff;
}
void DriveTrain::ToggleFrontBack(){
	driveFront = !driveFront;
}
void DriveTrain::Crab(float radian, float speed) {
	
		position = 485 + 485/pi*radian; //converts radians to counts for encoders
			
	
		SetSteerSetpoint(position, position, position, position);
		SetDriveSpeed(speed, -speed, speed, -speed);
}
void DriveTrain::Steer(float radian, float speed, float a) {
	
	A=a;
	
	thetaRC = pi - radian;  //convert steering angle to rear center wheel angle
	
	if(thetaRC != pi / 2)	//If we are not driving straight forward...
	{
		if(thetaRC < pi / 2)	//Right Turn
		{
			this->RightTurn4Wheels();
		}
		else if(thetaRC > pi / 2)	//Left Turn
		{
			this->LeftTurn4Wheels();
		}
	}
	else	//thetaRC = pi / 2
	{
		thetaFL = pi / 2;
		thetaFR = pi / 2;
		thetaRL = pi / 2;
		thetaRR = pi / 2;
		FLRatio = 1;
		FRRatio = 1;
		RLRatio = 1;
		RRRatio = 1;
	}
	//Solve for fastest wheel speed
	double speedarray[] = {fabs(FL), fabs(FR), fabs(RL), fabs(RR)};
		
	 int length = 4;
     double maxspeed = speedarray[0];
     for(int i = 1; i < length; i++)
     {
          if(speedarray[i] > maxspeed)
                maxspeed = speedarray[i];
     }
		 
	//Set ratios based on maximum wheel speed
	FLRatio = FL/maxspeed;
	FRRatio = FR/maxspeed;
	RLRatio = RL/maxspeed;
	RRRatio = RR/maxspeed;
	
	//Set drive speeds
	SetDriveSpeed(-FLRatio*speed, FRRatio*speed, -RLRatio*speed, RRRatio*speed);
	
	//Set Steering PID Setpoints
	float FLSetPoint = (242 + 485/pi*thetaFL);
	float FRSetPoint = (242 + 485/pi*thetaFR);
	float RLSetPoint = (242 + 485/pi*thetaRL);
	float RRSetPoint = (242 + 485/pi*thetaRR);
	
	SetSteerSetpoint(FLSetPoint, FRSetPoint, RLSetPoint, RRSetPoint);
	}
void DriveTrain::LeftTurn4Wheels()
{
	Z = ((A * X) * tan(pi - thetaRC));				//pi was subtracted out of this earlier
	
	thetaRL = pi - atan((Z - W) / (A * X));
	thetaRR = pi - atan((Z + W) / (A * X));
	thetaFR = pi / 2;
	thetaFL = pi / 2;
	
	if(A != 1)
	{
		thetaFL = atan((Z - Y) / ((1 - A) * X));	//These are identical for right and left turns
		thetaFR = atan((Z + Y) / ((1 - A) * X));	//These are identical for right and left turns
	}
	//Solve for radii (wheel speed)
	FL = (Z - Y) / sin(thetaFL);
	FR = (Z + Y) / sin(thetaFR);
	RL = (Z - W) / sin(pi - thetaRL);
	RR = (Z + W) / sin(pi - thetaRR);
}
void DriveTrain::RightTurn4Wheels()
{	
	Z = ((A * X) * tan(thetaRC));				//pi was subtracted out of this earlier
	
	thetaRL = atan((Z + W) / (A * X));
	thetaRR = atan((Z - W) / (A * X));
	thetaFR = pi / 2;
	thetaFL = pi / 2;
	
	if(A != 1)
	{
		thetaFR = pi - atan((Z - Y) / ((1 - A) * X));	//These are identical for right and left turns
		thetaFL = pi - atan((Z + Y) / ((1 - A) * X));	//These are identical for right and left turns
	}
	
	FL = (Z + Y) / sin(pi - thetaFL);
	FR = (Z - Y) / sin(pi - thetaFR);
	RL = (Z + W) / sin(thetaRL);
	RR = (Z - W) / sin(thetaRR);
}
int DriveTrain::CorrectSteerSetpoint(int setpoint) {
	
	
if (setpoint < 0)
{
	return setpoint + 970;
}
else if (setpoint > 970)
{
	return setpoint - 970;
}
else if (setpoint == 970)
{
	return 0;
}
else
{
	return setpoint;
}
}
void DriveTrain::SetSteerSetpoint(float FLSetPoint, float FRSetPoint, float RLSetPoint, float RRSetPoint)
{	
	if(driveFront) {
		
		if(fabs((int)FLSetPoint + FLOffset - frontLeftPos->GetAverageValue()) < 242 || fabs((int)FLSetPoint + FLOffset - frontLeftPos->GetAverageValue()) > 768)
		{
			frontLeft->SetSetpoint(CorrectSteerSetpoint((int)FLSetPoint + FLOffset));
			FLInv = 1;
		}
			else
		{
			frontLeft->SetSetpoint(CorrectSteerSetpoint((int)FLSetPoint + FLOffset-485));
			FLInv = -1;
		}
		
		if(fabs((int)FRSetPoint + FROffset - frontRightPos->GetAverageValue()) < 242 || fabs((int)FRSetPoint + FROffset - frontRightPos->GetAverageValue()) > 768)
		{
			frontRight->SetSetpoint(CorrectSteerSetpoint((int)FRSetPoint + FROffset));
			FRInv = 1;
		}
			else
		{
			frontRight->SetSetpoint(CorrectSteerSetpoint((int)FRSetPoint + FROffset-485));
			FRInv = -1;
		}
		
		if(fabs((int)RLSetPoint + RLOffset - rearLeftPos->GetAverageValue()) < 242 || fabs((int)RLSetPoint + RLOffset - rearLeftPos->GetAverageValue()) > 768)
		{
			rearLeft->SetSetpoint(CorrectSteerSetpoint((int)RLSetPoint + RLOffset));
			RLInv = 1;
		}
			else
		{
			rearLeft->SetSetpoint(CorrectSteerSetpoint((int)RLSetPoint + RLOffset-485));
			RLInv = -1;
		}
		
		if(fabs((int)RRSetPoint + RROffset - rearRightPos->GetAverageValue()) < 242 || fabs((int)RRSetPoint + RROffset - rearRightPos->GetAverageValue()) > 768)
		{
			rearRight->SetSetpoint(CorrectSteerSetpoint((int)RRSetPoint + RROffset));
			RRInv = 1;
		}
			else
		{
			rearRight->SetSetpoint(CorrectSteerSetpoint((int)RRSetPoint + RROffset-485));
			RRInv = -1;
		}
	
	}
	
	else {
	
		if(fabs((int)RRSetPoint + FLOffset - frontLeftPos->GetAverageValue()) < 242 || fabs((int)RRSetPoint + FLOffset - frontLeftPos->GetAverageValue()) > 768)
		{
			frontLeft->SetSetpoint(CorrectSteerSetpoint((int)RRSetPoint + FLOffset));
			FLInv = 1;
		}
			else
		{
			frontLeft->SetSetpoint(CorrectSteerSetpoint((int)RRSetPoint + FLOffset-485));
			FLInv = -1;
		}
		
		if(fabs((int)RLSetPoint + RLOffset - frontRightPos->GetAverageValue()) < 242 || fabs((int)RLSetPoint + FROffset - frontRightPos->GetAverageValue()) > 768)
		{
			frontRight->SetSetpoint(CorrectSteerSetpoint((int)RLSetPoint + FROffset));
			FRInv = 1;
		}
			else
		{
			frontRight->SetSetpoint(CorrectSteerSetpoint((int)RLSetPoint + FROffset-485));
			FRInv = -1;
		}
		
		if(fabs((int)FRSetPoint + RLOffset - rearLeftPos->GetAverageValue()) < 242 || fabs((int)FRSetPoint + RLOffset - rearLeftPos->GetAverageValue()) > 768)
		{
			rearLeft->SetSetpoint(CorrectSteerSetpoint((int)FRSetPoint + RLOffset));
			RLInv = 1;
		}
			else
		{
			rearLeft->SetSetpoint(CorrectSteerSetpoint((int)FRSetPoint + RLOffset-485));
			RLInv = -1;
		}
		
		if(fabs((int)FLSetPoint + RROffset - rearRightPos->GetAverageValue()) < 242 || fabs((int)FLSetPoint + RROffset - rearRightPos->GetAverageValue()) > 768)
		{
			rearRight->SetSetpoint(CorrectSteerSetpoint((int)FLSetPoint + RROffset));
			RRInv = 1;
		}
			else
		{
			rearRight->SetSetpoint(CorrectSteerSetpoint((int)FLSetPoint + RROffset-485));
			RRInv = -1;
		}
	}
		
		
}
void DriveTrain::SetDriveSpeed(float FLSpeed, float FRSpeed, float RLSpeed, float RRSpeed) {
	
	if(driveFront) {
		frontLeftDrive->Set(FLSpeed*FLInv);
		frontRightDrive->Set(FRSpeed*FRInv);
		rearLeftDrive->Set(RLSpeed*RLInv);
		rearRightDrive->Set(RRSpeed*RRInv);
	}
	else {
		frontLeftDrive->Set(RRSpeed*FLInv);
		frontRightDrive->Set(RLSpeed*FRInv);
		rearLeftDrive->Set(FRSpeed*RLInv);
		rearRightDrive->Set(FLSpeed*RRInv);
	}
}
void DriveTrain::Pivot(float twistinput, float speedinput)
{
	
	robotangle = (gyroscope->GetAngle())*2*pi/180;
	
	radius = sqrt(pow(Y,2)/4+pow(X,2)/4);
	
	FLWP = pi + atan(Y/X);
	FRWP = pi - atan(Y/X);
	RRWP = atan(W/X);
	RLWP = 2*pi - atan(W/X);
	
	if(fabs(twistinput) + fabs(speedinput) < 1)
		{
		velocity = maxspeed*speedinput;
		angularvelocity = maxspeed*twistinput/radius;
		}
	else
		{
		velocity = maxspeed*speedinput/(fabs(twistinput)+fabs(speedinput));
		angularvelocity = maxspeed*twistinput/(radius*(fabs(twistinput)+fabs(speedinput)));
		}
	
	if(FLWP + robotangle > 2*pi)
		FLPos = FLWP + robotangle -2*pi;
	else if(FLWP + robotangle < 0)
			FLPos = FLWP + robotangle + 2*pi;
		else
			FLPos = FLWP + robotangle;
	
	if(FRWP + robotangle > 2*pi)
		FRPos = FRWP + robotangle -2*pi;
	else if(FRWP + robotangle < 0)
			FRPos = FRWP + robotangle + 2*pi;
		else
			FLPos = FLWP + robotangle;
	
	if(RRWP + robotangle > 2*pi)
		RRPos = RRWP + robotangle -2*pi;
	else if(RRWP + robotangle < 0)
			RRPos = RRWP + robotangle + 2*pi;
		else
			RRPos = RRWP + robotangle;
	
	if(RLWP + robotangle > 2*pi)
		RLPos = RLWP + robotangle -2*pi;
	else if(RLWP + robotangle < 0)
			RLPos = RLWP + robotangle + 2*pi;
		else
			RLPos = RLWP + robotangle;
			
	FLXVel = velocity-radius*angularvelocity*sin(FLPos);		
	FRXVel = velocity-radius*angularvelocity*sin(FRPos);
	RRXVel = velocity-radius*angularvelocity*sin(RRPos);
	RLXVel = velocity-radius*angularvelocity*sin(RLPos);
		
	FLYVel = radius*angularvelocity*cos(robotangle+FLWP);
	FRYVel = radius*angularvelocity*cos(robotangle+FRWP);
	RRYVel = radius*angularvelocity*cos(robotangle+RRWP);
	RLYVel = radius*angularvelocity*cos(robotangle+RLWP);
	
	FLVel = sqrt(pow(FLXVel,2)+pow(FLYVel,2));
	FRVel = sqrt(pow(FRXVel,2)+pow(FRYVel,2));
	RLVel = sqrt(pow(RLXVel,2)+pow(RLYVel,2));
	RRVel = sqrt(pow(RRXVel,2)+pow(RRYVel,2));
		 
	//Set ratios based on maximum wheel speed
	FLRatio = FL/maxspeed;
	FRRatio = FR/maxspeed;
	RLRatio = RL/maxspeed;
	RRRatio = RR/maxspeed;
	
	//Set drive speeds
	SetDriveSpeed(-FLRatio, FRRatio,-RLRatio,RRRatio);
		
	if(FLXVel <= 0)
		if(FLPos < pi/2)
			deltaFL = atan(FLYVel/FLXVel) + pi;
		else
			deltaFL = atan(FLYVel/FLXVel) - pi;
	else
		deltaFL = atan(FLYVel/FLXVel);
	
	if(FRXVel <= 0)
		if(FRPos < pi/2)
			deltaFR = atan(FRYVel/FRXVel) + pi;
		else
			deltaFR = atan(FRYVel/FRXVel) - pi;
	else
		deltaFR = atan(FRYVel/FRXVel);
		
	if(RRXVel <= 0)
		if(RRPos < pi/2)
			deltaRR = atan(RRYVel/RRXVel) + pi;
		else
			deltaRR = atan(RRYVel/RRXVel) - pi;
	else
		deltaRR = atan(RRYVel/RRXVel);
	if(RLXVel <= 0)
		if(RLPos < pi/2)
			deltaRL = atan(RLYVel/RLXVel) + pi;
		else
			deltaRL = atan(RLYVel/RLXVel) - pi;
	else
		deltaRL = atan(RLYVel/RLXVel);
		
	
	if(2*pi - robotangle + deltaFL > 2*pi)
		thetaFL = 2*pi - robotangle + deltaFL - 2*pi;
	else if(2*pi - robotangle + deltaFL < 0)
			thetaFL = 2*pi - robotangle + deltaFL + 2*pi;
		else
			thetaFL = 2*pi - robotangle + deltaFL;
		
	if(2*pi - robotangle + deltaFR > 2*pi)
		thetaFR = 2*pi - robotangle + deltaFR - 2*pi;
	else if(2*pi - robotangle + deltaFR < 0)
			thetaFR = 2*pi - robotangle + deltaFR + 2*pi;
		else
			thetaFR = 2*pi - robotangle + deltaFR;
	if(2*pi - robotangle + deltaRR > 2*pi)
		thetaRR = 2*pi - robotangle + deltaRR - 2*pi;
	else if(2*pi - robotangle + deltaRR < 0)
			thetaRR = 2*pi - robotangle + deltaRR + 2*pi;
		else
			thetaRR = 2*pi - robotangle + deltaRR;
	if(2*pi - robotangle + deltaRL > 2*pi)
		thetaRL = 2*pi - robotangle + deltaRL - 2*pi;
	else if(2*pi - robotangle + deltaRL < 0)
			thetaRL = 2*pi - robotangle + deltaRL + 2*pi;
		else
			thetaRL = 2*pi - robotangle + deltaRL;
		
	SetSteerSetpoint(floor(485/pi*thetaFL),floor(485/pi*thetaFR),floor(485/pi*thetaRL),floor(485/pi*thetaRR));
}
void DriveTrain::CurrentLimit(){
	float currentlimit = 100;
	float currenttimeout = 1.5;
	float timeoutreset = 1.5;
	if(frontLeft->IsEnabled() && frontLeftSteer->GetOutputCurrent() > currentlimit){
		if(FLSOTimer < GetClock()){
			FLSOTimer = GetClock()+currenttimeout;
		}
		else{
			frontLeft->Disable();
			FLSOTimer = GetClock() + timeoutreset;
			}
	}
	
	if(!frontLeft->IsEnabled() && FLSOTimer > GetClock())
		frontLeft->Enable();
	
	if(frontRight->IsEnabled() && frontRightSteer->GetOutputCurrent() > currentlimit){
		if(FRSOTimer < GetClock()){
			FRSOTimer = GetClock()+currenttimeout;
		}
		else{
			frontRight->Disable();
			FRSOTimer = GetClock() + timeoutreset;
			}
	}
	
	if(!frontRight->IsEnabled() && FRSOTimer > GetClock())
		frontRight->Enable();
	
	if(rearRight->IsEnabled() && rearRightSteer->GetOutputCurrent() > currentlimit){
		if(RRSOTimer < GetClock()){
			RRSOTimer = GetClock()+currenttimeout;
		}
		else{
			rearRight->Disable();
			RRSOTimer = GetClock() + timeoutreset;
			}
	}
	
	if(!rearRight->IsEnabled() && RLSOTimer > GetClock())
		rearRight->Enable();
	
	if(rearLeft->IsEnabled() && rearLeftSteer->GetOutputCurrent() > currentlimit){
		if(RLSOTimer < GetClock()){
			RLSOTimer = GetClock()+currenttimeout;
		}
		else{
			rearLeft->Disable();
			RLSOTimer = GetClock() + timeoutreset;
			}
	}
	
	if(!rearLeft->IsEnabled() && RLSOTimer > GetClock())
		rearLeft->Enable();
		
}
bool DriveTrain::ZeroGyro(float InitTime)
{
	bool Done = false;
	
	if(GyroZeroFlag == false)
	{
		GyroZeroFlag = true;
		GyroZeroTime = GetClock();
	}
	else
	{
		if(GetClock() > GyroZeroTime + InitTime)
		{
			gyroscope->InitGyro();
			GyroZeroFlag = false;
			Done = true;
		}
	}
	
	return GetClock() > GyroZeroTime + InitTime + 6;
}
